name: Pre-commit checks

on:
    push:
        branches: [main, test-*]
        paths:
            - '**.py'

    pull_request:
        paths:
            - '**.py'

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v3
              with:
                python-version: 3.11

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install requirements/dev

            - name: Run Ruff
              run: |
                ruff src/

            - name: Run mypy
              run: |
                mypy src/

            - name: Run Pytest
              run: |
                pytest src/
